name: User of the backend
server.port=8080
logging.level.root=INFO
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
server.error.include-stacktrace=never
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1
